### ISSUE TITLE
Add support for algorithm specification

### ISSUE THREAD

**Issue by zpalmtree** [turtlecoin/violetminer#2]
https://github.com/xmrig/xmrig-proxy/blob/master/doc/STRATUM_EXT.md#1-mining-algorithm-negotiation

This will allow xmrig-proxy to validate shares being sent to it. Will also need to add argon support to xmrig-proxy.

**Comment by brandonlehmann** [comment]
> This will allow xmrig-proxy to validate shares being sent to it. Will also need to add argon support to xmrig-proxy.

see: https://github.com/Bendr0id/xmrigcc-donation-proxy/commit/bd152590490653c97adda13f184693483d86895f

**Comment by zpalmtree** [comment]
How does this proxy differ from xmrig-proxy?

**Comment by brandonlehmann** [comment]
> How does this proxy differ from xmrig-proxy?

I haven't reviewed the full commit history; however, I believe it's largely just a fork that's ahead of xmrig-proxy at the moment.

**Comment by zpalmtree** [comment]
If it supports chukwa hash validation out of the box then that's one less thing I have to do so sounds good if that's the case.

**Comment by brandonlehmann** [comment]
Define "hash validation" as I do not believe that xmrig-proxy supports full hash validation. It's *basic* validation only per https://github.com/xmrig/xmrig-proxy/wiki/Comparison

**Comment by zpalmtree** [comment]
I don't know what basic hash validation means really.. Right now I'm submitting chukwa shares to xmrig-proxy which thinks I'm submitting cryptonight-turtle - it does not complain and submits them to the pool in turn, which accepts them. 

I want xmrig-proxy to detect invalid shares before submitting them to the pool - otherwise, a single invalid miner could cause the whole proxy to be banned. Surely this is not the case for normal usage?

**Comment by brandonlehmann** [comment]
> I want xmrig-proxy to detect invalid shares before submitting them to the pool - otherwise, a single invalid miner could cause the whole proxy to be banned. Surely this is not the case for normal usage?

Actually, that's exactly the case :) I've had it happen myself. It doesn't do hash validation and that's where its speed comes from IIRC.

**Comment by zpalmtree** [comment]
This won't do what I thought it will do so closing for now.
