### ISSUE TITLE
After Donate miner crash

### ISSUE THREAD

**Issue by CHINuit** [turtlecoin/violetminer#33]
If i use ssl connection port after donate when miner reconnect to basic pool miner crash (Nvidia mine Only)

**Comment by zpalmtree** [comment]
Thanks for the report. Do you have an example of a pool you experience this issue with?

**Comment by CHINuit** [comment]
turtlecoin.herominers.com:10385 first discover this, after i try on
trtl.pool.mine2gether.com:5443(ssl port) if i don't use ssl(3335) miner don't stop after donate

**Comment by zpalmtree** [comment]
Thank you, I will investigate.

**Comment by CHINuit** [comment]
pls add "log.txt" support for next issues
