### ISSUE TITLE
windows  v0.2.0  can not start work

### ISSUE THREAD

**Issue by netmebtc** [turtlecoin/violetminer#38]
![image](https://user-images.githubusercontent.com/32667839/95723071-503a4580-0ca7-11eb-8f17-0bfbbe36d704.png)

OS: windows 10 profession 1903
RAM: 32G
CPU： Intel  XEON E5-2680v2 (2 core)

**Comment by zpalmtree** [comment]
Are you using a GPU? You may need to update your nvidia drivers to support the newest version of cuda.

**Comment by netmebtc** [comment]
My rig hs no nvidia card, and I only run with cpu as following cmd:
ioletminer  --disableNVIDIA  --disableAMD --threads 20 --algorithm turtlecoin --pool trtl-test.cnpool.cc:32616 --username TRTLv2Fyavy8CXG8BPEbNeCHFZ1fuDCYCZ3vW5H5LXN4K2M2MHUpTENip9bbavpHvvPwb4NDkBWrNgURAd5DB38FHXWZyoBh4wW --password x

But it still can not start working

**Comment by netmebtc** [comment]
![image](https://user-images.githubusercontent.com/32667839/96423006-57bf9880-122b-11eb-9470-47aa912335ac.png)
I just recompile it with   the -DENABLE_NVIDIA=OFF flag: `cmake -DENABLE_NVIDIA=OFF  ..`， and it can working now.

Seeems the `-disableNVIDIA`  is not real disable NVDIA mining

**Comment by zpalmtree** [comment]
Yep, there was a bug where the nvidia code wasn't getting correctly disabled. It will be fixed in the next release.
