### ISSUE TITLE
Crash on Donation 

### ISSUE THREAD

**Issue by richard2012uk** [turtlecoin/violetminer#39]
Please look at your code for donation , I dont mind contrabuting to your code .

BUT IT CRASHES MY CLIENT !!!! Due to you asking client for out of bounds algo 

So please stop this / or fix it 

please also add logging so I can upload this here when your Donation Crashes My Client ....

Thank you for your work

**Comment by RocksteadyTC** [comment]
calm down lad.

**Comment by zpalmtree** [comment]
Sorry to hear that. Are you able to post any screenshot of what you describe as "Due to you asking client for out of bounds algo"

I have been meaning to add logging.

When mining directly to the donation server I do see it working fine, and I'm also seeing other client successfully submitting shares. I do see a number however submitting invalid shares, which could be from miners that are un-updated or potentially bugged clients.

I have removed dev mining in the latest build.

**Comment by CHINuit** [comment]
this miner is a joke ? start miner with 22kh/s and in 1 min go down to 5-7,5kh/s...

**Comment by richard2012uk** [comment]
Hi , I don't have any screen shots yet but will post when it next happens .

Logging would be really helpful if thats something you could implament soon !

I'm cool with donating to your time and code , and sorry if I sounded angry but i'm not .

From what I remember the client stops due to the algo being off height , it eccepts jobs on donation and parsses some but then stops .

I will screen shot when this happens again .

Also on a side note could this client be ported / used on Hiveos ?

Thank you for your time

**Comment by zpalmtree** [comment]
> Also on a side note could this client be ported / used on Hiveos ?

I'm not really sure what HiveOS requires, does it need an API to communicate with?

**Comment by richard2012uk** [comment]
In Hiveos you can port any miner under a tag "superminer" if it will run in linux , not sure about API .

I'm a little new to the whole minning thing but am a keen to learn 

https://hiveos.farm/getting_started-start_custom_miner/

Would love to use your miner on this ..

**Comment by richard2012uk** [comment]
Hi ,
If you could port this / make alittle more stable you will be the first that offer Nvida support !

All the other miners are CPU / AMD 

So currently your the best :) 

Thank you

**Comment by richard2012uk** [comment]
Screen shot , this time no crash ..... AS I stopped it mining ! 

![Screenshot (2)](https://user-images.githubusercontent.com/4012825/97091347-49122080-1633-11eb-8ef0-d03dbe87175e.png)

**Comment by zpalmtree** [comment]
This looks like the way to integrate a miner with hiveOS: https://github.com/minershive/hiveos-linux/blob/master/hive/miners/custom/README.md

As far as I can tell, it doesn't need any changes to the miner, just those scripts to be written

**Comment by richard2012uk** [comment]
Hi , 
Cool I will look into it , its a great miner just needs the above screen shot fixed ! 

cheers

**Comment by zpalmtree** [comment]
You can try this binary for one without dev fee mining https://github.com/turtlecoin/violetminer/suites/1393624464/artifacts/23073091

It's a bit concerning you're seeing rejected shares when mining on the dev pool, it should be using the same algo as regular mining, and that's demonstrated by the fact that only a few of the shares are being rejected.

Are you seeing any rejected shares while mining on your pool of choice, or only when the donation mining occurs?

**Comment by richard2012uk** [comment]
Hi , 
No I never get rejected shares on my pool , It only happens on Donate some times so much it Kills the client due to the time .

I will try the client as above , but I only GPU mine so hope it works.

Thank you

**Comment by richard2012uk** [comment]
Hi , I have that client running now if I have issue I will screen shot and update you .

Logging would be very helpful as I want to contrabute to your time and code .

Thank you for your help I will update here in the next 24 hours .

cheers
