### ISSUE TITLE
the provided PTX was compiled with an unsupported toolchain.

### ISSUE THREAD

**Issue by Dylstructor** [turtlecoin/violetminer#41]
how do i fix it?

**Comment by zpalmtree** [comment]
What nvidia driver version are you using? You may be using a version too old for the cuda version.

**Comment by Dylstructor** [comment]
> What nvidia driver version are you using? You may be using a version too old for the cuda version.

I am using the latest one i can get by doing: pacman -S cuda

**Comment by Dylstructor** [comment]
how do i get the version number?

**Comment by zpalmtree** [comment]
`sudo pacman -Qs nvidia`

**Comment by Dylstructor** [comment]
local/cuda 11.1.1-1
    NVIDIA's GPU programming toolkit
local/cudnn 8.0.5.39-1
    NVIDIA CUDA Deep Neural Network library
local/lib32-libvdpau 1.4-1
    Nvidia VDPAU library
local/lib32-nvidia-450xx-utils 450.80.02-1
    NVIDIA drivers utilities (32-bit)
local/libvdpau 1.4-1
    Nvidia VDPAU library
local/libxnvctrl 455.38-1
    NVIDIA NV-CONTROL X extension
local/linux58-nvidia-450xx 450.80.02-5 (linux58-extramodules)
    NVIDIA drivers for linux.
local/mhwd-nvidia-340xx 340.108-1
    MHWD module-ids for nvidia 340.108
local/mhwd-nvidia-390xx 390.132-1
    MHWD module-ids for nvidia 390.132
local/mhwd-nvidia-418xx 418.113-1
    MHWD module-ids for nvidia-418xx 418.113
local/mhwd-nvidia-430xx 430.64-1.0
    MHWD module-ids for nvidia-430xx 430.64
local/mhwd-nvidia-435xx 435.21-1.0
    MHWD module-ids for nvidia 435.21
local/mhwd-nvidia-440xx 440.100-1
    MHWD module-ids for nvidia 440.100
local/mhwd-nvidia-450xx 450.80.02-1
    MHWD module-ids for nvidia 450.80.02
local/mhwd-nvidia-455xx 455.45.01-1
    MHWD module-ids for nvidia 455.45.01
local/nccl 2.7.8-3
    Library for NVIDIA multi-GPU and multi-node collective communication primitives
local/nvidia-450xx-utils 450.80.02-1
    NVIDIA drivers utilities
local/opencl-nvidia-450xx 450.80.02-1
    OpenCL implemention for NVIDIA
local/pycuda-headers 2020.1-1
    Python wrapper for Nvidia CUDA
local/python-pycuda 2020.1-1
    Python wrapper for Nvidia CUDA
local/xf86-video-nouveau 1.0.16-2 (xorg-drivers)
    Open Source 3D acceleration driver for nVidia cards

**Comment by zpalmtree** [comment]
Hmm, I don't seem to see `local/nvidia` in there unless i'm scanning over it - this is what I get, you can see I have `local/nvidia 455.45.01-2` installed:

```
local/cuda 11.1.1-1
    NVIDIA's GPU programming toolkit
local/egl-wayland 1.1.5+2+g9c9c4c6-1
    EGLStream-based Wayland external platform
local/lib32-nvidia-utils 455.45.01-1
    NVIDIA drivers utilities (32-bit)
local/libnvidia-container 1.3.0-1
    NVIDIA container runtime library
local/libnvidia-container-tools 1.3.0-1
    NVIDIA container runtime library
local/libvdpau 1.4-1
    Nvidia VDPAU library
local/libxnvctrl 455.45.01-1
    NVIDIA NV-CONTROL X extension
local/nvidia 455.45.01-2
    NVIDIA drivers for linux
local/nvidia-container-runtime 3.4.0-1
    NVIDIA opencontainer runtime fork to expose GPU devices to containers.
local/nvidia-container-toolkit 1.3.0-1
    NVIDIA container runtime toolkit
local/nvidia-docker 2.5.0-1
    Build and run Docker containers leveraging NVIDIA GPUs
local/nvidia-settings 455.45.01-1
    Tool for configuring the NVIDIA graphics driver
local/nvidia-utils 455.45.01-1
    NVIDIA drivers utilities
local/opencl-nvidia 455.45.01-1
    OpenCL implemention for NVIDIA
```

You could try compiling yourself, it may be easier than trying to match driver versions with the released binary. There is a `turtlecoin-git` package in the `AUR`,

**Comment by Dylstructor** [comment]
i will try using the turtlecoin-git :+1:

**Comment by zpalmtree** [comment]
Crap, typo, I mean `violetminer-git`

**Comment by Dylstructor** [comment]
ok lol :P

**Comment by Dylstructor** [comment]
awww still didnt work :(

**Comment by Dylstructor** [comment]
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  /var/tmp/pamac-build-dylan/violetminer-git/src/violetminer/src/Argon2/src/Nvidia/Argon2.cu(827): cudaErrorUnsupportedPtxVersion: the provided PTX was compiled with an unsupported toolchain.
full error btw

**Comment by Dylstructor** [comment]
just if that helps

**Comment by zpalmtree** [comment]
If it fails when compiled with local packages, then that makes me think you have a cuda / nvidia driver version that is mismatched for sure.

Does `pacman -Qi nvidia` give any output?

**Comment by Dylstructor** [comment]
Name            : linux58-nvidia-450xx
Version         : 450.80.02-5
Description     : NVIDIA drivers for linux.
Architecture    : x86_64
URL             : http://www.nvidia.com/
Licenses        : custom                                                                                                                                                                       
Groups          : linux58-extramodules                                                                                                                                                         
Provides        : nvidia=450.80.02                                                                                                                                                             
Depends On      : linux58  nvidia-450xx-utils=450.80.02
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : linux58-nvidia-340xx  linux58-nvidia-390xx  linux58-nvidia-418xx  linux58-nvidia-430xx  linux58-nvidia-435xx  linux58-nvidia-440xx
Replaces        : None
Installed Size  : 12.95 MiB
Packager        : Helmut Stult <helmut@manjaro.org>
Build Date      : Sun 01 Nov 2020 09:09:55 AM CST
Install Date    : Sun 29 Nov 2020 05:37:25 PM CST
Install Reason  : Explicitly installed
Install Script  : Yes
Validated By    : Signature

**Comment by zpalmtree** [comment]
Ah, that makes more sense. CUDA 11.1 requires a later nvidia driver version than that: 

![image](https://user-images.githubusercontent.com/22151537/100556937-b3a32580-329d-11eb-8340-92b83763109c.png)

It looks like you're using manjaro - it's possible 455.23 or greater are not yet in your repos, in which case you would need to downgrade CUDA instead to get the compilation working.

**Comment by Dylstructor** [comment]
oh can you give me the command to do that?

**Comment by Dylstructor** [comment]
im kinda a noob :rofl:

**Comment by zpalmtree** [comment]
You could try https://wiki.archlinux.org/index.php/Downgrading_packages, but I'm not sure if that is directly applicable to manjaro.

Something like `sudo pacman -U /var/cache/pacman/pkg/cuda-10.2.89-5-x86_64.pkg.tar.zst` would work if you had CUDA 10.2 already downloaded from a previous upgrade. But that upgrade would fail on my system without downgrading some other packages, so you may experience the same issue.

**Comment by zpalmtree** [comment]
If the latest nvidia driver *are* in your repos, it should be as easy as just updating your nvidia driver and recompiling, however.

**Comment by Dylstructor** [comment]
Ok i will try updating the nvidia driver. and get back to you! Thank you in advance!

**Comment by Dylstructor** [comment]
Huh when i update graphics drivers it pops up with Error: config 'video-nvidia-455xx' conflicts with config(s): video-nvidia-450xx on manjaro-settings-manager ;/

**Comment by Dylstructor** [comment]
do you know how to fix this?

**Comment by Dylstructor** [comment]
Oh wait! It is installing :+1: i will get back to you when it is done

**Comment by Dylstructor** [comment]
Hey! I got it working!
