### ISSUE TITLE
Accepted share 0 nvidia geforce mx110

### ISSUE THREAD

**Issue by MShawon** [turtlecoin/violetminer#45]
Nvidia geforce mx110 supports cuda 11.2...it is not accepting any share. I tried to compile myself with cuda 11.2 still no luck.

**Comment by zpalmtree** [comment]
From my research the `mx110` is based on the `GM 108` chip which is a first gen maxwell chip. From my experience, cards of this generation do not work with the bundled violetminer cuda, which is 11.1.

Shares not being accepted doesn't necessarily mean it's not working on your card - you could be using the wrong algorithm for the pool.

**Comment by MShawon** [comment]
It's working with CPU but when I use --disableCPU, then no share is accepting. Then I compiled with Cuda 11.2 also but not working.

if I use xmrig for CPU or CryptoDredge for GPU it's working. But I guess violetminer will work at a time both on CPU and GPU. So I really wanted to use violetminer.

**Comment by zpalmtree** [comment]
It looks like cryptodredge releases binaries with cuda `10.2` and cuda `9.2`. I'm not sure if compiling with cuda 10.x or 9.x would work, but you could try that if you want.

**Comment by MShawon** [comment]
okay, I will give it a try.
