### ISSUE TITLE
windows cmd stop the output

### ISSUE THREAD

**Issue by robinfoxnan** [turtlecoin/violetminer#51]
anybody who uses windows should add code like these:
`void setModeCmd()
{
#ifdef WIN32
	HANDLE hStdin = GetStdHandle(STD_INPUT_HANDLE);
	DWORD mode;
	GetConsoleMode(hStdin, &mode);

	mode &= ~ENABLE_QUICK_EDIT_MODE; // 移除快速编辑模式
	mode &= ~ENABLE_INSERT_MODE;     // 移除插入模式
	mode &= ~ENABLE_MOUSE_INPUT;

	SetConsoleMode(hStdin, mode);
#else
	//std::cout << "";
#endif // WIN32
}`

**Comment by robinfoxnan** [comment]
i was confused for a month, the miner would block at somewhere,
and go on when hit anykey, 
i debug it many times, but no change,
this morning , i searthed  std::out block in baidu.com, so i got it

**Comment by zpalmtree** [comment]
I think there's also a terminal option to block input from the mouse in Windows.
