### ISSUE TITLE
Can't build - No CUDA toolset found

### ISSUE THREAD

**Issue by b8engl** [turtlecoin/violetminer#52]
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19043.
-- The CXX compiler identification is MSVC 19.29.30038.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30037/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.20/Modules/CMakeDetermineCompilerId.cmake:441 (message):
  No CUDA toolset found.
Call Stack (most recent call first):
  C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.20/Modules/CMakeDetermineCompilerId.cmake:6 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.20/Modules/CMakeDetermineCompilerId.cmake:58 (__determine_compiler_id_test)
  C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.20/Modules/CMakeDetermineCUDACompiler.cmake:278 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:11 (enable_language)

**Comment by zpalmtree** [comment]
Do you have CUDA installed? Are you trying to compile for a Nvidia GPU? Getting cmake to find your cuda install on windows is really annoying. 

You will probably need to set the path to the cuda toolset like is done here: https://github.com/turtlecoin/violetminer/blob/master/scripts/win-install.bat#L1-L10

**Comment by b8engl** [comment]
I was pointing to ...\CUDA\v11.3\bin and not the main version folder.
Thanks buddy!

**Comment by b8engl** [comment]
Don't know why but was getting the following error `CMake Error at CMakeLists.txt:11 (enable_language):`
Nedded to copy and past the content from `...CUDA\v11.3\extras\visual_studio_integration\MSBuildExtensions` to `...Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\BuildCustomizations`

**Comment by b8engl** [comment]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools>cd c:\violetminer && rmdir /s /q build && mkdir build && cd build && cmake -G "Visual Studio 16 2019" .. && MSBuild violetminer.sln /p:Configuration=Release /m
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19043.
-- The CXX compiler identification is MSVC 19.29.30038.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30037/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The CUDA compiler identification is NVIDIA 11.3.109
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.3/bin/nvcc.exe - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- The C compiler identification is MSVC 19.29.30038.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30037/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Found OpenSSL: optimized;C:/OpenSSL-Win64/lib/VC/static/libeay32MT.lib;debug;C:/OpenSSL-Win64/lib/VC/static/libeay32MTd.lib (found version "1.0.2u")
-- OpenSSL Found: C:/OpenSSL-Win64/include
-- Processor: AMD64
-- Target Architecture: x86_64
-- Using x86 specific code
-- Enabling Windows style /arch:AVX flags
-- Nvidia
-- Configuring done
-- Generating done
-- Build files have been written to: C:/violetminer/build
Microsoft (R) Build Engine version 16.10.2+857e5a733 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

**Comment by b8engl** [comment]
@zpalmtree do I need to have a diferent build?

**Comment by b8engl** [comment]
16 Warning(s)
104 Error(s)

**Comment by b8engl** [comment]
Please see my output log in zip file at
https://easyupload.io/y9370f

**Comment by b8engl** [comment]
"C:\violetminer\build\violetminer.sln" (default target) (1) ->
       "C:\violetminer\build\ALL_BUILD.vcxproj.metaproj" (default target) (2) ->
       "C:\violetminer\build\src\Argon2\src\Nvidia\Nvidia.vcxproj.metaproj" (default target) (12) ->
       "C:\violetminer\build\src\Argon2\src\Nvidia\Nvidia.vcxproj" (default target) (26) ->
       "C:\violetminer\build\src\Argon2\src\Nvidia\Nvidia.vcxproj" (CudaBuildCore target) (26:2) ->
         C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\include\xutility(1309): error : expected a "(" [C:\violetminer\build\src\Argon2\src\Nvidia\Nvidia.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\include\xutility(1310): error : identifier "_Verify_range" is undefined [C:\violetminer\build\src\Argon2\src\Nvi
       dia\Nvidia.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\include\xutility(1309): error : expected a "(" [C:\violetminer\build\src\Argon2\src\Nvidia\Nvidia.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\include\xutility(1310): error : identifier "_Verify_range" is undefined [C:\violetminer\build\src\Argon2\src\Nvi
       dia\Nvidia.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\include\xutility(1309): error : expected a "(" [C:\violetminer\build\src\Argon2\src\Nvidia\Nvidia.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\include\xutility(1310): error : identifier "_Verify_range" is undefined [C:\violetminer\build\src\Argon2\src\Nvi
       dia\Nvidia.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\include\xutility(1309): error : expected a "(" [C:\violetminer\build\src\Argon2\src\Nvidia\Nvidia.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\include\xutility(1310): error : identifier "_Verify_range" is undefined [C:\violetminer\build\src\Argon2\src\Nvi
       dia\Nvidia.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\include\xutility(1309): error : expected a "(" [C:\violetminer\build\src\Argon2\src\Nvidia\Nvidia.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\include\xutility(1310): error : identifier "_Verify_range" is undefined [C:\violetminer\build\src\Argon2\src\Nvi
       dia\Nvidia.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\include\xutility(1309): error : expected a "(" [C:\violetminer\build\src\Argon2\src\Nvidia\Nvidia.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\include\xutility(1310): error : identifier "_Verify_range" is undefined [C:\violetminer\build\src\Argon2\src\Nvi
       dia\Nvidia.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\include\xutility(1309): error : expected a "(" [C:\violetminer\build\src\Argon2\src\Nvidia\Nvidia.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\include\xutility(1310): error : identifier "_Verify_range" is undefined [C:\violetminer\build\src\Argon2\src\Nvi
       dia\Nvidia.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\include\xutility(1309): error : expected a "(" [C:\violetminer\build\src\Argon2\src\Nvidia\Nvidia.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\include\xutility(1310): error : identifier "_Verify_range" is undefined [C:\violetminer\build\src\Argon2\src\Nvi
       dia\Nvidia.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\include\xutility(1309): error : expected a "(" [C:\violetminer\build\src\Argon2\src\Nvidia\Nvidia.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\include\xutility(1310): error : identifier "_Verify_range" is undefined [C:\violetminer\build\src\Argon2\src\Nvi
       dia\Nvidia.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\include\xmemory(62): error : expected a "(" [C:\violetminer\build\src\Argon2\src\Nvidia\Nvidia.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\include\xutility(131): error : expected a "(" [C:\violetminer\build\src\Argon2\src\Nvidia\Nvidia.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\include\xstring(2881): error : expected a "(" [C:\violetminer\build\src\Argon2\src\Nvidia\Nvidia.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\include\xmemory(308): error : expected a "(" [C:\violetminer\build\src\Argon2\src\Nvidia\Nvidia.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\include\xmemory(959): error : expected a "(" [C:\violetminer\build\src\Argon2\src\Nvidia\Nvidia.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\include\xmemory(308): error : expected a "(" [C:\violetminer\build\src\Argon2\src\Nvidia\Nvidia.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\include\xmemory(959): error : expected a "(" [C:\violetminer\build\src\Argon2\src\Nvidia\Nvidia.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\include\xutility(1236): error : class "std::iterator_traits<char>" has no member "value_type" [C:\violetminer\bu
       ild\src\Argon2\src\Nvidia\Nvidia.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\include\xmemory(961): error : operand of "*" must be a pointer but has type "char" [C:\violetminer\build\src\Arg
       on2\src\Nvidia\Nvidia.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\include\xmemory(62): error : expected a "(" [C:\violetminer\build\src\Argon2\src\Nvidia\Nvidia.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\include\xutility(131): error : expected a "(" [C:\violetminer\build\src\Argon2\src\Nvidia\Nvidia.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\include\xstring(2881): error : expected a "(" [C:\violetminer\build\src\Argon2\src\Nvidia\Nvidia.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\include\xmemory(308): error : expected a "(" [C:\violetminer\build\src\Argon2\src\Nvidia\Nvidia.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\include\xmemory(959): error : expected a "(" [C:\violetminer\build\src\Argon2\src\Nvidia\Nvidia.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\include\xmemory(308): error : expected a "(" [C:\violetminer\build\src\Argon2\src\Nvidia\Nvidia.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\include\xmemory(959): error : expected a "(" [C:\violetminer\build\src\Argon2\src\Nvidia\Nvidia.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\include\xutility(1236): error : class "std::iterator_traits<__wchar_t>" has no member "value_type" [C:\violetmin
       er\build\src\Argon2\src\Nvidia\Nvidia.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\include\xmemory(961): error : operand of "*" must be a pointer but has type "__wchar_t" [C:\violetminer\build\sr
       c\Argon2\src\Nvidia\Nvidia.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\include\xutility(131): error : expected a "(" [C:\violetminer\build\src\Argon2\src\Nvidia\Nvidia.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\include\xmemory(62): error : expected a "(" [C:\violetminer\build\src\Argon2\src\Nvidia\Nvidia.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\include\xutility(131): error : expected a "(" [C:\violetminer\build\src\Argon2\src\Nvidia\Nvidia.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\include\xutility(1326): error : expected a "(" [C:\violetminer\build\src\Argon2\src\Nvidia\Nvidia.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\include\xutility(1328): error : expected a "(" [C:\violetminer\build\src\Argon2\src\Nvidia\Nvidia.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\include\xutility(1329): error : expression must have class type but it has type "char *" [C:\violetminer\build\s
       rc\Argon2\src\Nvidia\Nvidia.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\include\xutility(1326): error : expected a "(" [C:\violetminer\build\src\Argon2\src\Nvidia\Nvidia.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\include\xutility(1328): error : expected a "(" [C:\violetminer\build\src\Argon2\src\Nvidia\Nvidia.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\include\xutility(1329): error : expression must have class type but it has type "__wchar_t *" [C:\violetminer\bu
       ild\src\Argon2\src\Nvidia\Nvidia.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\include\atomic(368): error : expected a "(" [C:\violetminer\build\src\Argon2\src\Nvidia\Nvidia.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\include\atomic(370): error : expected a "(" [C:\violetminer\build\src\Argon2\src\Nvidia\Nvidia.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\include\atomic(371): error : invalid type conversion [C:\violetminer\build\src\Argon2\src\Nvidia\Nvidia.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\include\atomic(368): error : expected a "(" [C:\violetminer\build\src\Argon2\src\Nvidia\Nvidia.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\include\atomic(370): error : expected a "(" [C:\violetminer\build\src\Argon2\src\Nvidia\Nvidia.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\include\xmemory(927): error : expected a "(" [C:\violetminer\build\src\Argon2\src\Nvidia\Nvidia.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\BuildCustomizations\CUDA 11.3.targets(785,9): error MSB3721: O comando ""C:\Program Files\NVIDIA GPU Computing T
       oolkit\CUDA\v11.3\bin\nvcc.exe" -gencode=arch=compute_52,code=\"sm_52,compute_52\" --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\bin\Hos
       tX64\x64" -x cu -rdc=true  -IC:\violetminer\src\Argon2\src -IC:\violetminer\src -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include" -I"C:\OpenSSL-Win64\include" -I"C:\Program Files\NVIDI
       A GPU Computing Toolkit\CUDA\v11.3\include"     --keep-dir x64\Release  -maxrregcount=0  --machine 64 --compile -cudart static -std=c++14 -Xcompiler="/EHsc -Ob2"   -D_WINDOWS -DNDEBUG -DNVIDIA_ENABLED -D
       X86_OPTIMIZATIONS -DSOCKETWRAPPER_OPENSSL_SUPPORT -D"CMAKE_INTDIR=\"Release\"" -D"CMAKE_INTDIR=\"Release\"" -D_MBCS -Xcompiler "/EHsc /W3 /nologo /O2 /FdC:\violetminer\build\src\Argon2\src\Nvidia\Release
       \Nvidia.pdb /FS   /MD /GR" -o Nvidia.dir\Release\Blake2.obj "C:\violetminer\src\Argon2\src\Nvidia\Blake2.cu"" foi encerrado com o código 1. [C:\violetminer\build\src\Argon2\src\Nvidia\Nvidia.vcxproj]

**Comment by zpalmtree** [comment]
I haven't seen this error before, it seems like there's a syntax error in a library header file, which doesn't seem to make much sense. I had a lot of trouble getting windows compiling successfully - and I have only done it using github actions, rather than on a windows install myself.

For that reason I would suggest matching as much of your build environment to the github actions file for windows: https://github.com/turtlecoin/violetminer/blob/master/.github/workflows/matrix.yml#L218

Sorry I can't provide much more assistance than that.

**Comment by b8engl** [comment]
I will look in to replicate the steps in matrix.yml also I will do a clean install using chocolatey.
You have helped me! Thanks buddy!
