### ISSUE TITLE
Support for Argon2 multiple threads for CPU

### ISSUE THREAD

**Issue by yeungjackson** [turtlecoin/violetminer#54]
The code for running Argon2 using multiple lanes is there. However, it is not used to support multithreading. The number of Argon2 threads is hardcoded to 1 in Variants.h. Is it a design choice or a limitation of the ChukwaV2 spec? I would think sharing the same piece of scratchpad among multiple threads would causes less cache miss than each thread having their own scratchpad. Each ChukwaV2 scratchpad is 1MB in size.

**Comment by zpalmtree** [comment]
The 'threads' value corresponds to the parallelism parameter in the argon2 paper: https://raw.githubusercontent.com/P-H-C/phc-winner-argon2/master/argon2-specs.pdf
Therefore modifying this value would result in incorrect hashes for the chukwav2 spec, which specifies a parallelism of 1. You can see that [here.](https://github.com/turtlecoin/turtlecoin/blob/development/src/crypto/hash.h#L58)

Now, neither of those prevent you from sharing memory between threads. Having a preallocated, possibly huge paged mapped chunk of memory could certainly speed up hashing.

**Comment by yeungjackson** [comment]
Thanks for the explaination. So the threads value are implemented according the argon2 specification.  However chukwav2 only support threads = 1.

**Comment by zpalmtree** [comment]
Correct.
