### ISSUE TITLE
Cant connect to unminable pools!

### ISSUE THREAD

**Issue by OfflinePing** [turtlecoin/violetminer#56]
Seems to be banned from Unminable, is there any fix?

**Comment by zpalmtree** [comment]
What crypto are you trying to mine? I don't see TurtleCoin on the Uninable website. If you're trying to mine cryptocurrencies using an algorithm not supported by violetminer, it won't work.

If you got banned most likely you were sending rejected shares. Most likely cause is using the wrong algorithm, so make sure that is correct before reconnecting. TurtleCoin uses `chukwav2`

Most pools will unban you after 10-30 minutes or so. Try another pool, you can add multiple pools to your config and violetminer will attempt to reconnect, so once you get unbanned, it should auto reconnect to your pool of choice.

**Comment by OfflinePing** [comment]
i used it on Tron coin and it hat crazy high hashrates :/

**Comment by OfflinePing** [comment]
The ban is sadly permanent soo :(
