### ISSUE TITLE
CPU working too hot always at full load

### ISSUE THREAD

**Issue by gssondemon** [turtlecoin/violetminer#59]
Can you give it a CPU workload control feature, so we can desire the workload of the processor?
otherwise, it's a good program to use.

**Comment by zpalmtree** [comment]
Check out the `hardwareConfiguration` section of the config. https://docs.turtlecoin.lol/guides/mining/violetminer-guide#hardwareconfiguration

Assuming you have more than one core, lowering the `threadCount` should decrease CPU load and thus temperatures.

**Comment by gssondemon** [comment]
it works much better thank you.
