### ISSUE TITLE
How Much For AMD Radeon Support?

### ISSUE THREAD

**Issue by marcel1974** [turtlecoin/violetminer#60]
How Much For AMD Radeon Support? $$$
Have lots and lots of these cards?
Timeframe?

**Comment by zpalmtree** [comment]
Hi,
Thank you for the offer, unfortunately I do not have any time to dedicate to this project, even if paid well :disappointed: 
You could maybe contact the developer of https://github.com/turtlecoin/ninjarig, https://github.com/bogdanadnan, to update that miner to support the latest algorithm changes. I believe it has OpenCL and thus AMD support.

Best of luck on your search, friend
