### ISSUE TITLE
Don't keep submitting with the same invalid job ID

### ISSUE THREAD

**Issue by zpalmtree** [turtlecoin/violetminer#7]
On receiving `Invalid job id` we need to either wait for a new job from the pool, or attempt a re-login. Perhaps messages are getting lost somehow...

**Comment by brandonlehmann** [comment]
That’s what sending the `getjob` method is for :)

**Comment by zpalmtree** [comment]
I have not read anything about this method ;o

**Comment by brandonlehmann** [comment]
https://github.com/turtlecoin/node-turtle-pool/blob/dcb44b1fbc69af7abf5f0962d61db4ee10f4c00c/lib/pool.js#L587

Just send `getjob` no params

**Comment by zpalmtree** [comment]
Nice, this is much better than the hacky solution I was going to do. Do you know if nodejs pools support this method too?

**Comment by brandonlehmann** [comment]
https://github.com/dvandal/cryptonote-nodejs-pool/blob/f370ffeb407dec7e88f15fe7c5b80dc0175a9740/lib/pool.js#L622

Appears so.

**Comment by zpalmtree** [comment]
Implemented in v0.0.3
