### ISSUE TITLE
add gpu support

### ISSUE THREAD

**Issue by ExtraHash** [turtlecoin/violetminer#9]
:ooh_hoo_hoo_eggdra:

**Comment by zpalmtree** [comment]
go for it

**Comment by zpalmtree** [comment]
Nvidia support in progress

**Comment by selimaz** [comment]
Hi , and ati support?

**Comment by zpalmtree** [comment]
@selimaz Once Nvidia support is completed, this will be next on the list.

**Comment by zpalmtree** [comment]
You can track nvidia progress here: https://github.com/turtlecoin/violetminer/tree/nvidia
It's currently hashing, but needs heavy optimization.

**Comment by selimaz** [comment]
Thx

**Comment by zpalmtree** [comment]
Nvidia support has now been merged in.
